version: '3.1'
services:   
  vs:
    build: ./
    volumes:
      - ./:/app
      - tmp:/tmp
    ports:
      - "3001:3001"
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
volumes:
  tmp: